version: '3.1'

services:

  mongo:
    image: mongo
    container_name: komplent-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: komplent
      MONGO_INITDB_ROOT_USERNAME: komplent
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - komplent-v-mongodb:/data/db
      - komplent-v-mongodb_config:/data/configdb
    ports:
      - 27017:27017

volumes:
  komplent-v-mongodb:
  komplent-v-mongodb_config: